import 'package:bookhero/model/comic_model.dart';

List<Comic> mockComics = [
  // Comic(
  //   title: "Superman",
  //   era: "New 52",
  //   yearRange: "2011-2015",
  //   comicType: "Singles",
  //   issues: [
  //     Issue(
  //       issueNumber: 1,
  //       obtained: false,
  //       tags: ["First Issue"],
  //       event: "Trinity War",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //     Issue(
  //       issueNumber: 2,
  //       obtained: true,
  //       tags: ["Variant Cover"],
  //       event: "None",
  //       coverType: "Foil Cover",
  //       variant: "Limited Edition",
  //       specialEdition: "Annual",
  //     ),
  //     Issue(
  //       issueNumber: 3,
  //       obtained: false,
  //       tags: ["Trinity War"],
  //       event: "Trinity War",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //     Issue(
  //       issueNumber: 4,
  //       obtained: true,
  //       tags: ["Darkseid War"],
  //       event: "Darkseid War",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //   ],
  // ),
  // Comic(
  //   title: "Batman",
  //   era: "Rebirth",
  //   yearRange: "2016-2020",
  //   comicType: "Mini-Series",
  //   issues: [
  //     Issue(
  //       issueNumber: 1,
  //       obtained: false,
  //       tags: ["Annual"],
  //       event: "None",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "Annual",
  //     ),
  //     Issue(
  //       issueNumber: 2,
  //       obtained: true,
  //       tags: ["Foil Cover"],
  //       event: "None",
  //       coverType: "Foil Cover",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //     Issue(
  //       issueNumber: 3,
  //       obtained: false,
  //       tags: ["Forever Evil"],
  //       event: "Forever Evil",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //   ],
  // ),
  // Comic(
  //   title: "Justice League",
  //   era: "New 52",
  //   yearRange: "2011-2016",
  //   comicType: "Trade",
  //   issues: [
  //     Issue(
  //       issueNumber: 1,
  //       obtained: false,
  //       tags: ["Doomed"],
  //       event: "Doomed",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //     Issue(
  //       issueNumber: 2,
  //       obtained: true,
  //       tags: ["Darkseid War"],
  //       event: "Darkseid War",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //     Issue(
  //       issueNumber: 3,
  //       obtained: false,
  //       tags: ["Trinity War"],
  //       event: "Trinity War",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //   ],
  // ),
  // Comic(
  //   title: "Wonder Woman",
  //   era: "Infinite Frontier",
  //   yearRange: "2021-Present",
  //   comicType: "Singles",
  //   issues: [
  //     Issue(
  //       issueNumber: 1,
  //       obtained: true,
  //       tags: ["New Beginning"],
  //       event: "None",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //     Issue(
  //       issueNumber: 2,
  //       obtained: false,
  //       tags: ["Crossover"],
  //       event: "Crossover",
  //       coverType: "Standard",
  //       variant: "None",
  //       specialEdition: "None",
  //     ),
  //     Issue(
  //       issueNumber: 3,
  //       obtained: false,
  //       tags: ["Foil Cover"],
  //       event: "None",
  //       coverType: "Foil Cover",
  //       variant: "Special Edition",
  //       specialEdition: "None",
  //     ),
  //   ],
  // ),
];
